brew "coreutils"
brew "eza"
brew "fzf"
brew "git"
brew "gum"
brew "hitblast/tap/cutler"
brew "libyaml"
brew "readline"
brew "ripgrep"
brew "stow"
brew "tmux"
brew "tree-sitter"

cask "1password"
cask "brave-browser"
cask "docker"
cask "drawio"
cask "ghostty"
cask "google-chrome"
cask "insomnia"
cask "spotify"
cask "visual-studio-code"

cask "font-fira-code-nerd-font"
cask "font-jetbrains-mono-nerd-font"

vscode "catppuccin.catppuccin-vsc"
vscode "hediet.vscode-drawio"
vscode "ms-azuretools.vscode-docker"
vscode "tamasfe.even-better-toml"
