#!/usr/bin/env zsh

OMACASE_DIR="$(cd "$(dirname "${BASE_SOURCE[0]}")" &> /dev/null && pwd)"

echo -e "This script will require sudo access at various points. Enter your password below..."
sudo -v

if [ ! -f /opt/homebrew/bin/brew ]; then
	# Homebrew is the simplest package manager for macOS. I looked at Nix and Nix-Darwin but it just feels too complicated for what's needed
	NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
fi

# Make sure that we can use Homebrew on the PATH
eval "$(/opt/homebrew/bin/brew shellenv)"

while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

brew bundle --file $OMACASE_DIR/install/brewfile
for installer in install/*.install.sh; do source $installer; done
unset installer

desktoppr $HOME/.local/share/omacase/theme/omacase-bg.jpg
