#!/usr/bin/env zsh

alias c="clear"

alias vim="nvim"
alias n="nvim"

alias ls="eza -lg --group-directories-first --icons=always"
alias ll="ls"
alias la="ls -a"
alias lt="eza --tree --level-3 --long --icons --git"
alias lta="lt -a"

alias cd="z"
