after-login-command = []
after-startup-command = []

start-at-login = true

enable-normalization-flatten-containers = true
enable-normalization-opposite-orientation-for-nested-containers = true

accordion-padding = 30

default-root-container-layout = "tiles"
default-root-container-orientation = "auto"

key-mapping.preset = "qwerty"

on-focused-monitor-changed = ["move-mouse monitor-lazy-center"]

[gaps]
inner.horizontal = 15
inner.vertical   = 15
outer.left       = 15
outer.bottom     = 15
outer.top        = 15
outer.right      = 15

[mode.main.binding]

cmd-shift-f = "fullscreen"

cmd-shift-space = "move-workspace-to-monitor --wrap-around next"

alt-h = "focus left"
alt-j = "focus down"
alt-k = "focus up"
alt-l = "focus right"

cmd-shift-1 = "workspace 1"
cmd-shift-2 = "workspace 2"
cmd-shift-3 = "workspace 3"
cmd-shift-b = "workspace B" # Web [B]rowser
cmd-shift-t = "workspace T" # [T]erminal
cmd-shift-o = "workspace O" # [O]ffice apps
cmd-shift-m = "workspace M" # [M]usic
cmd-shift-e = "workspace E" # [E]mail

alt-shift-1 = "move-node-to-workspace 1"
alt-shift-2 = "move-node-to-workspace 2"
alt-shift-3 = "move-node-to-workspace 3"
alt-shift-b = "move-node-to-workspace B"
alt-shift-t = "move-node-to-workspace T"
alt-shift-o = "move-node-to-workspace O"
alt-shift-m = "move-node-to-workspace M"
alt-shift-e = "move-node-to-workspace E"

cmd-shift-semicolon = "mode service"

[mode.service.binding]
esc = ["reload-config", "mode main"]
r = ["flatten-workspace-tree", "mode main"] # reset layout
backspace = ["close-all-windows-but-current", "mode main"]

[[on-window-detected]]
if.app-id = "com.mitchellh.ghostty"
run = "move-node-to-workspace T"

[[on-window-detected]]
if.app-id = "com.google.Chrome"
run = "move-node-to-workspace B"

[[on-window-detected]]
if.app-id = "com.spotify.client"
run = "move-node-to-workspace M"

[[on-window-detected]]
if.app-id = "com.microsoft.Outlook"
run = "move-node-to-workspace E"

[[on-window-detected]]
if.app-id = "com.microsoft.teams2"
run = "move-node-to-workspace O"

[[on-window-detected]]
if.app-id = "com.tinyspeck.slackmacgap"
run = "move-node-to-workspace O"
