#!/usr/bin/env zsh

BASE_DIR="$HOME/Work"
CLIENT_NAME=$(gum input --prompt "What's the client name? (PascalCase) " --placeholder "e.g KirkDave, BJSS")
PROJECT_NAME=$(gum input --prompt "What's the name of the project? (PascalCase) " --placeholder "e.g. NewProjectName")

CLIENT_DIR="$BASE_DIR/Clients/$CLIENT_NAME"
PROJECT_DIR="$CLIENT_DIR/$PROJECT_NAME"

if [ -d $$PROJECT_DIR ]; then
    echo -e "$(tput setf 3)The project $PROJECT_NAME already exists for client $CLIENT_NAME$(tput sgr0)"
    return
fi

mkdir -p "$CLIENT_DIR/_Shared/"
mkdir -p "$CLIENT_DIR/_Shared/Commercial"
mkdir -p "$CLIENT_DIR/_Shared/Context"
mkdir -p "$CLIENT_DIR/_Shared/References"

mkdir -p "$PROJECT_DIR/Architecture"
mkdir -p "$PROJECT_DIR/Engineering"
mkdir -p "$PROJECT_DIR/Design"
mkdir -p "$PROJECT_DIR/Commercial"
mkdir -p "$PROJECT_DIR/References"

echo -e "Project directory $PROJECT_DIR created"
