[[ -z "$XDG_CACHE_HOME" ]] && export XDG_CACHE_HOME=$HOME/.cache
[[ -z "$XDG_CONFIG_HOME" ]] && export XDG_CONFIG_HOME=$HOME/.config
[[ -z "$XDG_DATA_HOME" ]] && export XDG_DATA_HOME=$HOME/.local/share

[[ -r "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh" ]] && source "${XDG_CACHE_HOME}/p10k-instant-prompt-${(%):-%n}.zsh"

test -f $HOME/.local/share/omacase/defaults/shell/shell && source $HOME/.local/share/omacase/defaults/shell/shell
test -f $HOME/.local/share/omacase/defaults/shell/aliases && source $HOME/.local/share/omacase/defaults/shell/aliases
test -f $HOME/.local/share/omacase/defaults/shell/functions && source $HOME/.local/share/omacase/defaults/shell/functions
